# Generated by Django 4.0.10 on 2023-12-20 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='repost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
